"""
Django settings for plodyrolne project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+2$_v36nz=uwuy4@g!rhn9-on@d3e32az-5d!$&pp_=762)h$f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
		'szyszko.no-ip.org',
		'osgiliath',
		]


# Application definition
INSTALLED_APPS = (
		'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.messages',
		'django.contrib.staticfiles',
		'django.contrib.sites',
		'registration',
		'rejestracja',
		'rolnicy',
		'klasyfikacje',
		'wiadomosci',
		'django_markdown',
		'widget_tweaks',
		'location_field',
		'pagedown',
    'szukajka',
)

ACCOUNT_ACTIVATION_DAYS = 7
#?
#LOGIN_URL='/login'
#LOGIN_REDIRECT_URL='/rolnicy/mojprofil;'

MIDDLEWARE_CLASSES = (
		'django.contrib.sessions.middleware.SessionMiddleware',
		'django.middleware.common.CommonMiddleware',
		'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',
		'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'plodyrolne.urls'

TEMPLATES = [
		{
				'BACKEND': 'django.template.backends.django.DjangoTemplates',
				'DIRS': [os.path.join(PROJECT_PATH, 'templates')],
				'APP_DIRS': True,
				'OPTIONS': {
						'context_processors': [
								'django.template.context_processors.debug',
								'django.template.context_processors.request',
								'django.contrib.auth.context_processors.auth',
								'django.contrib.messages.context_processors.messages',
						],
				},
		},
]

WSGI_APPLICATION = 'plodyrolne.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
		'default': {
				'ENGINE': 'django.db.backends.sqlite3',
				'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
		}
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'pl-pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

USE_LOCAL_STATIC = True
if USE_LOCAL_STATIC:
		STATIC_URL= os.path.join(BASE_DIR, '/static/')
		STATIC_ROOT = STATIC_URL
else:
		STATIC_URL = 'http://szyszko.no-ip.org/static/'
		STATIC_ROOT = '/srv/http/static/'
#STATIC_URL = '/c/Users/nao/PythonProjects/plodyrolne/static/'
#STATIC_ROOT = '/c/Users/nao/PythonProjects/plodyrolne/static/'
STATICFILES_DIRS=(
		os.path.join(PROJECT_PATH, '../static'),
		)

SITE_ID=2

MARKDOWN_EXTENSIONS = 'extra', 'codehilite'
MARKDOWN_EXTENSION_CONFIGS = {
		'codehilite': {
				'linenums': False,
		}
}
